[package]
name = "devefi-icrc-reader"
version = "1.0.4"
description = "Read ICRC Ledger transaction log"
repository = "https://github.com/Neutrinomic/devefi_icrc_reader"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"